### ISSUE TITLE
Hashtag management

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bkper/bkper-issues#12]
```
Request Summary:
It would be nice to have some kind of hashtag management.
Enable the ledger owner to make hashtags show or not when posting transactions;
To change existing transactions' their hashtags.
(something like the labels idea in gmail.)



```

Original issue reported on code.google.com by `jacob...@lagaroo.com.br` on 23 Oct 2014 at 10:54

**Comment by maelcaldas** [comment]
We are finally working on building a UI to handle hashtag management. 

The initial idea is to manage on Accounts screen, adding a list of all hashtags on left menu, bellow the groups, with option to forget any tag any time, also, each transaction will have its tags used listed on main list on right, with ability to forget a tag from a specific account.

**Comment by maelcaldas** [comment]
After many tests, we decided to implement an internal hashtag management, with an algorithm that forgets stale hashtags automatically, based on last time used and usage times, per account.

We strongly believe a good automated hashtag management will be better for the end user and will make the clients much simpler.

The forced way to forget hashtags, by recording them with a minus signt (e.g. -#expense)  will continue to work, so, the user still have chance to control the system behavior

 We still working on improving this mechanism, so, any feedback will be really appreciated.
