### ISSUE TITLE
Display group balances on left-hand menu

### ISSUE THREAD

**Issue by jmgilman** [bkper/bkper-issues#45]
I've got a fairly advanced ledger with around 30 accounts in it and the left-hand menu is becoming increasingly cluttered. I've got all of my accounts broken into groups to help keep them organized and I would love to have the option to keep track of group balances in the left-hand menu rather than simply listing all of the accounts.

For instance, my cash group consists of 3 accounts. In order to see the status of that group I have to manually run a group query to get the totalized amount of all accounts in that group. Instead of having to manually run that query, it would be easier if I could just list all group total balances in the left-hand menu.

Personally, I think it would make sense to add a third dropdown:

* Transactions
* Accounts
* Groups

As a Gold subscriber, I would be willing to pay for this feature as it will save me a lot of time.

**Comment by maelcaldas** [comment]
Hi Joshua,

That totally make sense. We will prioritise it.

Thanks once more for your tips and support. That really helps us move in the right direction.

Cheers

**Comment by maelcaldas** [comment]
Some points:

Groups will only show balance, if **all its accounts are permanent**

Groups with non-permanent accounts will not show its balances on menu, since non-permanent accounts, such as Expense and Revenue only makes sense to query its balances in a window of time.

**Comment by jmgilman** [comment]
This makes sense to me.

What about groups with just non-permanent accounts? Would it make sense to
have those default to a running balance for the current week or month?
Might introduce too much complexity but it's just a thought.

On Fri, Jan 8, 2016 at 10:30 AM, Mael Caldas <notifications@github.com>
wrote:

> Some points:
>
> Groups will only show balance, if *all its accounts are permanent*
>
> Groups with non-permanent accounts will not show its balances on menu,
> since non-permanent accounts, such as Expense and Revenue only makes sense
> to query its balances in a window of time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkper/bkper-issues/issues/45#issuecomment-170083371>.
>



-- 
*Joshua Gilman*
*(707) 580 - 8473*

**Comment by maelcaldas** [comment]
We just released a new version with a complete reengineering of the menu, showing the permanent groups balances.

Some points:
- Only groups with all permanent accounts will be considered permanent and will show its balances
- Groups and accounts behave the same way it. You can select and open the charts or location (no more chart icon besides menu)
- To open/close a group now you must click in the arrow beside it
- Ordering priority for all itens:
  1) Permanent nature
  2) Frequency of usage


About the suggestion on running a balance for the current month, that would bring 2 big drawbacks:
- Latency to run a query every time you update the model 
- Complexity of logic for end user (What is permanent, what not?)
- Too many information on menu

So we decided not to add this at this time, and think more about how to address this suggestion.

**We will wait any suggestion and feedback about this improvement, before close it**

Thanks once more! :-)

**Comment by jmgilman** [comment]
HI Mael,

Excellent work, it looks great! I did notice a small front-end issue related to this change. When dropping down the arrow next to the group to see all of the associated accounts, I cannot scroll down the side menu if the accounts go all the way past the bottom of the menu. 

For example, my savings group has about 20 accounts in it and I can only see about half of them at the moment (because I cannot scroll down any further). 

I am using Chrome version 47.0.2526.106 (64-bit)

**Comment by jmgilman** [comment]
I can also confirm I see this issue on Firefox v43.0 build 20151208100201

**Comment by maelcaldas** [comment]
Wow! 

I just noticed it. I'm working on it now and will deploy a hotfix ASAP

**Comment by maelcaldas** [comment]
The hot bugfix is deployed! I hope it's working properly now!

Thanks once more! :-)

Any other comment or suggestion about this issue?

**Comment by jmgilman** [comment]
That fixed it on my end, thanks!

I like the idea of having the most used accounts at top, however it does make things somewhat confusing when you're looking for a specific group (since it's not in alphabetical order anymore). Perhaps we could either introduce an option to restore the list back to alphabetical order or add an option to allow the user to rearrange the accounts as they see fit? 

Hope that makes sense. Thanks again for the hard work!

**Comment by maelcaldas** [comment]
We are struggling to find the best way to address this ordering issue, without adding too much complexity to the user on configuring...

What about letting Groups ordered as the most used one, and, inside a specific group, let in alphabetical order?

**Comment by jmgilman** [comment]
That sounds like a better option at the moment. As I said, some of my groups have 20+ accounts in them so not being in alphabetical order does cause me to have to take an extra minute to two to run down the list and try to find the account I am looking for.

Perhaps we could add a search bar above the account list to allow us to filter the accounts based on typing in the box?

**Comment by maelcaldas** [comment]
We just released a version with this modification (needs page reload):

- The first level, groups and accounts without groups, are ordered by usage.
- **Inside each Group, accounts are ordered alphabetically**

**Please take a look and see if you don't need this extra minute anymore!**

About the search, actually when you click, you execute a search at the main search input. We have plans to add an autocomplete function to the main search (soon), so you can start typing and quick access the account, which will be selected on menu.

**Comment by jmgilman** [comment]
Hi Mael,

That's much better. I think the flow is much more smooth by having the accounts listed alphabetically.

I look forward to the autocomplete on the main search bar, I think that will help get to things slightly quicker. 

Quick question, with this new view, how do we get to the graphs for the groups? I thought before I could click on the group name and it would show the graphs for it, but I could be mistaken.

**Comment by maelcaldas** [comment]
Great!

I hope this works better for now! We will continue iterating over the menu (drag/drop etc)

I just filled an Issue for the Autocomplete:

https://github.com/bkper/bkper-issues/issues/47

Subscribe to this issue or add any comment to follow the implementation (we hope to start it soon)

About the graphs for groups now works the same way the graphs for accounts works... You need to toggle the report screen on the list action bar. Once the report opened, you can navigate over other groups and accounts, by clicking on it. You can do the opposite also, by selecting some group and opening the report... 

Does that make sense?

**Comment by jmgilman** [comment]
Ah, sorry, I must have missed that change. I found it :)

Thanks for the great work! :+1:

**Comment by maelcaldas** [comment]
Ok, great!

I will close this issue now, so, we can create others issues for others improvements!

Thanks for all your suggestions! That really helps us move in the right direction!

:+1:

**Comment by maelcaldas** [comment]
We just released updates related to this issue... Now menu ordering is always alphabetical, also, the state of menu is persisted in local browser storage, so it will keep which Groups are opened or closed when you come back to that Book later.

**Comment by jmgilman** [comment]
Awesome, thanks for the hard work!

On Mon, Feb 29, 2016 at 9:08 AM, Mael Caldas <notifications@github.com>
wrote:

> We just released updates related to this issue... Now menu ordering is
> always alphabetical, also, the state of menu is persisted in local browser
> storage, so it will keep which Groups are opened or closed when you come
> back to that Book later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkper/bkper-issues/issues/45#issuecomment-190293099>.
>



-- 
*Joshua Gilman*
*(707) 580 - 8473*

**Comment by maelcaldas** [comment]
Another improvement related to this issue just released: Now the left menu also shows non-permanent account's balances for current month
