### ISSUE TITLE
Report period balance and cumulative balance are misaligned by one unit of time

### ISSUE THREAD

**Issue by Onaka** [bkper/bkper-issues#46]
My first transactions are in 11/2014, but the automatic report interface shows 10/2014 as the first month, but with 11/2014's values. This skew is consistent, all the report values are shifted one month into the past.
If I try to look at a group or an account for a given year, the report will be accurate as far as I can tell, but show it as belonging to the year prior and clicking on the bar or line graph will produce a search query for the year prior.

**Comment by maelcaldas** [comment]
Hi Onaka,

Could you please tell what timezone you are fiscally, and what timezone is set in your Book Configurations?

You can find the timezone configurations here:

http://help.bkper.com/article/37-book-settings

**Comment by Onaka** [comment]
My timezone is GMT+2 Helsinki and my settings match.

**Comment by maelcaldas** [comment]
Can you please share a book, or a copy of the book with me, so we can reproduce the problem? My email is:

mael@bkper.com

**Comment by Onaka** [comment]
It has been shared with the comment https://github.com/bkper/bkper-issues/issues/46

**Comment by maelcaldas** [comment]
The issue was related to date formatting on web client. We were able to reproduce and fix it.
