### ISSUE TITLE
Can't load past transactions in bkper

### ISSUE THREAD

**Issue by alessandropetrone** [bkper/bkper-issues#48]
I have some issues with bkper. I cannot load transactions older than one month from the current date, even if I try by pressing the "load more" button at the bottom of the page.

My transaction history dates back 1st January 2016. No filter or query is actually active. Any idea?

I'm a bkper gold user.

**Comment by maelcaldas** [comment]
The transaction's paging was stuck, rolling at the same page indefinitely. This bug was introduced in the latest release on April 8, 2016 at 4:35pm, and fixed on April 9, 2016 1:56pm. (~22h after)
