### ISSUE TITLE
App hangs, unusable. 403 from API even though I'm logged in

### ISSUE THREAD

**Issue by arlobelshee** [bkper/bkper-issues#54]
Bkper stopped working for me. I think it happened when I changed my domains (and email addresses) for my user. I'm not sure about that, but I am getting 403s from api.bkper.com.

1. When I first come to the app, I see my existing ledger.
2. If I try to create a new ledger, I get the problem as soon as I choose a template and click create.
3. If I open my existing ledger, I get the problem as the ledger is loading.

Problem:
1. Spinner stays forever. Application busy-hangs (lots of JS is running).
2. Opening the console, I see a request to https://app.bkper.com/_ah/api/bkperbff/v0/books/agtzfmJrcGVyLWhyZHITCxIGTGVkZ2VyGICAgPD44KoKDA/load?limit=50&registerNewUser=false&ie_fix=1559932679907 that results in a 403.

I have already logged out of all Google accounts, then logged in just to this one account, via Bkper.

I am user arlobelshee2.

**Comment by arlobelshee** [comment]
In dev tools, I can see that the response to this (and any other API query) is

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Login Required."
   }
  ],
  "code": 403,
  "message": "Login Required."
 }
}
```

However, I am logged in - it shows my avatar image in the top-right, and does list my one ledger in the list of ledgers.

**Comment by arlobelshee** [comment]
During initial troubleshooting, I followed the instructions at https://help.bkper.com/troubleshooting/what-can-i-do-if-i-cant-i-log-in

Thus, I have currently revoked access to bkper. However, it was not able to re-request access.

Are you are storing the email address for the user (or something like that), and expecting to use it as a constant key? Or anything else that would have changed when I completely shifted my Google account? It is the same account, just with all identifiers changed.

**Comment by arlobelshee** [comment]
Interestingly, if I open a guest window in Chrome, then I have to do the login myself and I get a new user experience. I get dropped in with 0 ledgers.

So there is something about the Chrome login that is managing to associate with my active account in your system, but then that doesn't match the updates to my Google account. When I just come to your system via my current Google account directly, it sees that as a new user and creates a new account.

BTW, I'm guessing there is now a new account in your system with my current email address. So as part of this bug fix, please delete that account and use my old/existing account with the new email address.

**Comment by arlobelshee** [comment]
Note: the newly-created user then has the same problem, in the Chrome guest window. It also gets 403s for API requests, and hangs as soon as I try to create a new ledger.

**Comment by maelcaldas** [comment]
Hi Arlo,

Thanks for the detailed information and for the patience.

We actually track user by its ID from the Google Account, not the email, so, it was not expected to duplicate but, taking a deep look into both users, for some reason the ID came different from Google. Not sure why that happened. Looks like some operation on your Google Account lead to id changing... 

We can do this by moving book ownership to your new user, but we will need some security checkings before... Can you send us an email to contact@bkper.com from the old email address. If you changed your domain, I believe you can still use the old domain and create an email alias, and use this alias to send the message. A simple message requesting to move the book ownership and the user email of destination would be enough.

Would that work for you?

**Comment by maelcaldas** [comment]
Hi Arlo,

We released an improvement that aim to fix this issue.

Did you try to login again?

**Comment by arlobelshee** [comment]
It works. I am happy. :)

Arlo Belshee
Principal Technical and Leadership Agile Coach
arlo@belshee.com
http://arlobelshee.com/
@arlobelshee <https://twitter.com/arlobelshee>   in:arlobelshee
